### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by AmoghTiwari** [gauravsharma21/myweather-app#1]
Can you please elaborate a bit about how you gather location coordinates, in your readme?
I mean, do you enter the location name, and then find latitude and longitude or do you directly identify the location using the PCs IP address?

**Comment by gauravsharma21** [comment]
I fetch the name of location entered by user to mapbox.com API which returns the latitude and longitude of that location. The app doesn't have the functionality of using the user's current location, but the use of IP addresses for doing this is a great idea. I am looking forward to it. Thanks!!
